### ISSUE TITLE
jni 0.21 migration

### ISSUE THREAD

**Issue by cpu** [rustls/rustls-platform-verifier#22]
Presently this crate uses [`jni-rs`](https://github.com/jni-rs/jni-rs) v0.19 as an optional dependency for doc generation, and a required dependency for the Android OS target.

The latest release stream, 0.21.x, "makes extensive breaking changes in order to improve safety. Most projects that use this library will need to be changed accordingly.". The upstream project offers a [migration guide](https://github.com/jni-rs/jni-rs/blob/master/docs/0.21-MIGRATION.md) to help with this process.

Given the advertised safety improvements it's likely worthwhile to consider the steps required for migration.

**Comment by complexspaces** [comment]
Thanks for taking a glance at this! The new safety improvements look very welcome. Our uses are pretty simple so I'm hoping our upgrade path is pretty smooth.

**Comment by djc** [comment]
Yes.
