### ISSUE TITLE
GitHub CI using deprecated actions

### ISSUE THREAD

**Issue by cpu** [rustls/rustls-platform-verifier#26]
The CI workflows are currently using `actions-rs` tasks that are [unmaintained](https://github.com/actions-rs/toolchain/issues/216) and affected by GitHub's deprecation of Node 12.

> The following actions uses node12 which is deprecated and will be forced to run on node16: actions-rs/toolchain@v1, actions-rs/cargo@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

The following workflow task need to be replaced:

* `actions-rs/toolchain@v1` used by `ci.yaml`
* `actions-rs/cargo@v1` used by `ci.yaml`
* `actions-rs/audit-check@v1` used by `audit.yml`

In the other Rustls projects we've switched to https://github.com/dtolnay/rust-toolchain, but it doesn't offer an equivalent to `audit-check`. That one might require a separate 3rd party action.

**Comment by complexspaces** [comment]
`audit-check` is small enough we could probably utilize GitHub Actions cache and a manual `cargo-install` to accomplish the same thing. I'm in favor of migrating the other ones to Dtolnay's.

**Comment by djc** [comment]
What does audit-check do? Can we just pick up cargo-deny? It consumes the advisory database and helps with a bunch of other stuff, too.

**Comment by complexspaces** [comment]
I see `cargo-deny` as a superset of `cargo-audit`, so I don't see an issue with that if we have an easy way to utilize it in CI.

**Comment by djc** [comment]
#29 replaces audit-check with cargo-deny.
