### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by Ralith** [rustls/rustls-platform-verifier#53]
This is blocking Quinn from shipping rustls-platform-verifier helpers out of the box (https://github.com/quinn-rs/quinn/pull/1734). May be as simple as replacing `cfg(target_os = "linux")` with `cfg(all(unix, not(target_os = "macos"), not(target_os = "ios")))`.

**Comment by cpu** [comment]
That seems reasonable. I think the more interesting aspect will be CI coverage. It [looks like](https://github.com/quinn-rs/quinn/blob/55234e178fdca81cd51a5bfb520cb912de14f72e/.github/workflows/rust.yml#L11-L32) Quinn is using `vmactions/freebsd-vm@v1` for that. I suppose we should follow suit?

**Comment by complexspaces** [comment]
I agree this is just an oversight and FreeBSD support should be expected. `vmactions/freebsd-vm@v1` seems like it's pretty widely used on GitHub.

As for the proper gate, I think we want this for the `other.rs` module. Android has its own implementation, not just Apple's platforms:
```rust
cfg(all(unix, not(target_os = "android") not(target_os = "macos"), not(target_os = "ios")))
```

**Comment by cpu** [comment]
https://github.com/rustls/rustls-platform-verifier/pull/55
