### ISSUE TITLE
Fix Verifier struct required feature flag rendering in docs.rs

### ISSUE THREAD

**Issue by cpu** [rustls/rustls-platform-verifier#56]
@ralith pointed out that the `Verifier` struct is being rendered on `docs.rs` as "Available on Linux or WebAssembly only." - but that's not correct: each platform has its own version of this struct. At the time of writing this is visible [here](https://docs.rs/rustls-platform-verifier/latest/rustls_platform_verifier/struct.Verifier.html):

![bad](https://github.com/rustls/rustls-platform-verifier/assets/292650/37eb52fd-b414-41dd-9732-6fef55ea9662)

Each of the platforms has its own `pub use` of the `Verifier` struct in the `verification` mod:
https://github.com/rustls/rustls-platform-verifier/blob/a586af91c780cec83625fbe05dcc4ce9f1d7c567/rustls-platform-verifier/src/verification/mod.rs#L4-L5

https://github.com/rustls/rustls-platform-verifier/blob/a586af91c780cec83625fbe05dcc4ce9f1d7c567/rustls-platform-verifier/src/verification/mod.rs#L10-L11

https://github.com/rustls/rustls-platform-verifier/blob/a586af91c780cec83625fbe05dcc4ce9f1d7c567/rustls-platform-verifier/src/verification/mod.rs#L16-L17

https://github.com/rustls/rustls-platform-verifier/blob/a586af91c780cec83625fbe05dcc4ce9f1d7c567/rustls-platform-verifier/src/verification/mod.rs#L22-L23

I'm not sure why the Linux/WASM one is being rendered in docs.rs but not the others. I did some experimenting with adjusting the `cfg` gates like we do in `lib.rs` so [Android specific features are displayed](https://github.com/rustls/rustls-platform-verifier/blob/a586af91c780cec83625fbe05dcc4ce9f1d7c567/rustls-platform-verifier/src/lib.rs#L11-L15) but wasn't able to find a solution.

You can reproduce this locally, but must do so with nightly rust and the `doc_auto_cfg` feature enabled with:
```
RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc
```

Putting this issue in the tracker so that it's acknowledged as a known issue waiting for a fix.

**Comment by complexspaces** [comment]
It seems unlikely, but I wonder if this has anything to do with docs.rs only building docs for Linux by default: 
<img width="755" alt="image" src="https://github.com/rustls/rustls-platform-verifier/assets/68570223/598046f3-185c-44d4-8580-0c3fa5129364">

If I build the documentation locally on my Mac, I see `macOS or iOS` there instead, which implies its picking up assumptions based on the host's target:
<img width="936" alt="image" src="https://github.com/rustls/rustls-platform-verifier/assets/68570223/60d05e72-74b4-4d5a-91ab-ee588f3d638e">

**Comment by cpu** [comment]
That makes sense :+1: I've also been building on Linux.
