### ISSUE TITLE
The create is not published on crates.io?

### ISSUE THREAD

**Issue by neevek** [rustls/rustls-platform-verifier#6]
Hi, would you publish the crate on crates.io?

**Comment by complexspaces** [comment]
Hello there 👋.

I plan to publish this crate to crates.io in the short-term future, but there's still prep work to do in order to make the android implementation usable by downstream users first. Thanks for the request/interest though.

**Comment by neevek** [comment]
@complexspaces Great! Looking forward to seeing it to work on Android.
